// 采购商
const procurementFlag = "procurement";
export const procurement = [
  {
    path: "/supplier",
    name: "supplier",
    label: "供应商关联管理",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/khgl-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/supplier"),
  },
  {
    path: "/procurement-user",
    name: "procurementUser",
    label: "企业员工管理",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/qyyggl-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/employeeManage"),
  },
  {
    path: "/procurement-role",
    name: "procurementRole",
    label: "角色管理",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/roleManage"),
  },
  {
    path: "/buyer-information",
    name: "buyerInformation",
    label: "消息",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/information"),
  },
  {
    path: "/buyer-statementquery",
    name: "buyerstatementquery",
    label: "对账单查询",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/statementquery"),
  },
  {
    path: "/buyer-orderQuery",
    name: "buyerOrderQuery",
    label: "订单查询",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/orderQuery"),
  },
  {
    path: "/buyer-arrivalNoticeQuery",
    name: "buyerArrivalNoticeQuery",
    label: "到货通知单查询",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/arrivalNoticeQuery"),
  },
  {
    path: "/buyer-receivingQuery",
    name: "buyerReceivingQuery",
    label: "收货查询",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/receivingQuery"),
  },
  {
    path: "/buyer-salesReturnQuery",
    name: "buyerSalesReturnQuery",
    label: "退货单查询",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/salesReturnQuery"),
  },
  {
    path: "/buyerOrder",
    name: "buyerOrder",
    label: "订单下达",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/buyerOrder"),
  },
  {
    path: "/buyer-supplierorder",
    name: "buyercustomerorder",
    label: "供应商订货统计",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/customerorder"),
  },
  {
    path: "/buyer-suppliereturns",
    name: "buyercustomerreturns",
    label: "供应商退货统计",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/customerreturns"),
  },
  {
    path: "/buyer-suppliedelivery",
    name: "buyercustomerdelivery",
    label: "供应商发货统计",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/customerdelivery"),
  },
  {
    path: "/arrivalNoticeCommand",
    name: "ArrivalNoticeCommand",
    label: "到货通知单下达",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/arrivalNotice/arrivalNoticeCommand.vue"),
  },
  {
    path: "/takeOrder",
    name: "TakeOrder",
    label: "收货单",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/shd-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/takeOrder/index"),
  },
  {
    path: "/returnOrder",
    name: "ReturnOrder",
    label: "退货单",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/thd-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/returnOrder/index"),
  },
  {
    path: "/checkforFeedback",
    name: "CheckforFeedback",
    label: "对账反馈",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/dzfk-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/feedback.vue"),
  },
  {
    path: "/buyer-productioninventory",
    name: "/buyerproductioninventory",
    label: "生产计划与库存查询",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/scjh-bg.png"),
    flag: procurementFlag,
    component: () => import("@/views/buyer/productioninventory"),
  },
];
