// 供应商
const supplierFlag = "supplier";
export const supplier = [
  {
    path: "/customer",
    name: "customer",
    label: "客户关联管理",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/khgl-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/customer"),
  },
  {
    path: "/supplier-statementquery",
    name: "supplierstatementquery",
    label: "对账单查询",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/dzfk-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/statementquery.vue"),
  },
  {
    path: "/supplier-productionAndInventory",
    name: "supplieProductionAndInventory",
    label: "生产计划与库存",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/scjh-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/productionAndInventory"),
  },
  {
    path: "/supplier-purchaseOrderQuery",
    name: "supplierPurchaseOrderQuery",
    label: "订单查询",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddcx-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/purchaseOrderQuery.vue"),
  },
  {
    path: "/supplier-arrivalNoticeQuery",
    name: "supplierArrivalNoticeQuery",
    label: "到货通知单查询",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/dhtz-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/arrivalNoticeQuery.vue"),
  },
  {
    path: "/supplier-dispatchBillQuery",
    name: "supplierDispatchBillQuery",
    label: "发货单查询",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/fhd-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/dispatchBillQuery.vue"),
  },
  {
    path: "/supplier-salesReturnQuery",
    name: "supplierSalesReturnQuery",
    label: "退货单查询",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/thd-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/salesReturnQuery.vue"),
  },
  {
    path: "/supplier-user",
    name: "supplierUser",
    label: "企业员工管理",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/qyyggl-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/employeeManage"),
  },
  {
    path: "/supplier-role",
    name: "supplierRole",
    label: "角色管理",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/khgl-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/roleManage"),
  },
  {
    path: "/supplier-information",
    name: "supplierInformation",
    label: "消息",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/khgl-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/information"),
  },
  {
    path: "/dispatchBill",
    name: "BispatchBill",
    label: "发货单",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/fhd-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/dispatchBill/index"),
  },
  {
    path: "/reconciliation",
    name: "Reconciliation",
    label: "发起对账",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/fqdz-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/initiatereconciliation"),
  },
  {
    path: "/operatorreconciliation",
    name: "OperatorReconciliation",
    label: "发起对账",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/fqdz-bg.png"),
    flag: supplierFlag,
    component: () =>
      import("@/views/reconciliation/operatorreconciliation.vue"),
  },
  {
    path: "/salesReturnOrder",
    name: "SalesReturnOrder",
    label: "退货反馈",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/thfk-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/salesReturnOrder/index"),
  },
  {
    path: "/arrivalNotice",
    name: "ArrivalNotice",
    label: "到货通知单确认",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/dhtzxd-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/arrivalNotice/index"),
  },
  {
    path: "/supplier-productioninventory",
    name: "supplierproductioninventory",
    label: "生产计划与库存查询",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/scjh-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/productioninventory"),
  },
  {
    path: "/supplier-buyerorder",
    name: "suppliersupplierorder",
    label: "客户订货统计",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddqr-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/supplierorder"),
  },
  {
    path: "/supplier-buyerreturns",
    name: "suppliersupplierreturns",
    label: "客户退货统计",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/thfk-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/supplierreturns"),
  },
  {
    path: "/supplier-buyerdelivery",
    name: "suppliersupplierdelivery",
    label: "客户发货统计",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/fhd-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/supplierdelivery"),
  },
  {
    path: "/supplyOrder",
    name: "supplyOrder",
    label: "订单确认",
    urlImg: require("../assets/images/menu1.png"),
    bgIcon: require("../assets/images/ddqr-bg.png"),
    flag: supplierFlag,
    component: () => import("@/views/supply/supplyOrder"),
  },
];
